### ISSUE TITLE
1.0 checklist

### ISSUE THREAD

**Issue by MrBartusek** [MrBartusek/DokChat#33]
- [x] Update frontend API keys in config.ts
- [x] Remove all accounts
- [x] Revert QA commit
- [x] Google site verificaiton
